---
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
  
  - name: Open nginx port in UFW
    community.general.ufw:
      rule: allow
      name: 'Nginx Full'
  
  - name: Copy nginx config
    ansible.builtin.template:
      src: "{{ role_path }}/templates/pihole_nginx.conf.j2"
      dest: /etc/nginx/conf.d/pihole_nginx.conf

  # TODO
  # - SSL Certs