---
  - name: Stop pihole
    ansible.builtin.import_tasks:
      file: tag_stop.yml
  
  - name: Start pihole - should pull the latest version
    ansible.builtin.import_tasks:
      file: tag_start.yml

# TODO
# - Update dns definitions
# - Update config definitions